using UniGetUI.Core.Data;
using UniGetUI.Core.SettingsEngine;

namespace UniGetUI.Core.Tools.Tests;

public class InstallerDownloadLocationTests : IDisposable
{
    private readonly string _testRoot;

    public InstallerDownloadLocationTests()
    {
        _testRoot = Path.Combine(
            Path.GetTempPath(),
            nameof(InstallerDownloadLocationTests),
            Guid.NewGuid().ToString("N")
        );
        CoreData.TEST_DataDirectoryOverride = Path.Combine(_testRoot, "Data");
        CoreData.TEST_DownloadsDirectoryOverride = Path.Combine(_testRoot, "Downloads");
        Directory.CreateDirectory(CoreData.UniGetUIUserConfigurationDirectory);
        Settings.ResetSettings();
    }

    [Fact]
    public void NoCustomDirectoryIsSetByDefault()
    {
        Assert.Null(InstallerDownloadLocation.GetCustomDirectory());
        Assert.False(InstallerDownloadLocation.IsCustomDirectorySet);
        Assert.Null(InstallerDownloadLocation.ResolveStartDirectory());
    }

    [Theory]
    [InlineData("")]
    [InlineData("   ")]
    public void BlankCustomDirectoriesAreTreatedAsUnset(string stored)
    {
        Settings.SetValue(Settings.K.DefaultInstallerDownloadDirectory, stored);

        Assert.Null(InstallerDownloadLocation.GetCustomDirectory());
        Assert.False(InstallerDownloadLocation.IsCustomDirectorySet);
        Assert.Null(InstallerDownloadLocation.ResolveStartDirectory());
    }

    [Fact]
    public void AnUnsetCustomDirectoryStillDownloadsToTheDefaultOne()
    {
        string resolved = InstallerDownloadLocation.ResolveExistingDirectory();

        Assert.Equal(Path.Combine(_testRoot, "Downloads"), resolved);
        Assert.True(Directory.Exists(resolved));
    }

    [Fact]
    public void AnExistingCustomDirectoryIsUsed()
    {
        string custom = Path.Combine(_testRoot, "Installers");
        Directory.CreateDirectory(custom);
        InstallerDownloadLocation.SetCustomDirectory(custom);

        Assert.Equal(custom, InstallerDownloadLocation.GetCustomDirectory());
        Assert.True(InstallerDownloadLocation.IsCustomDirectorySet);
        Assert.Equal(custom, InstallerDownloadLocation.ResolveStartDirectory());
    }

    [Fact]
    public void ASelectedPathIsStoredWithoutBeingRewritten()
    {
        string custom = "/home/tester/installers ";
        InstallerDownloadLocation.SetCustomDirectory(custom);

        Assert.Equal(custom, InstallerDownloadLocation.GetCustomDirectory());
    }

    [Fact]
    public void AMissingCustomDirectoryLeavesTheStartLocationToTheSystem()
    {
        string custom = Path.Combine(_testRoot, "Gone");
        InstallerDownloadLocation.SetCustomDirectory(custom);

        Assert.Equal(custom, InstallerDownloadLocation.GetCustomDirectory());
        Assert.True(InstallerDownloadLocation.IsCustomDirectorySet);
        Assert.Null(InstallerDownloadLocation.ResolveStartDirectory());
    }

    [Fact]
    public void SettingANullCustomDirectoryClearsIt()
    {
        string custom = Path.Combine(_testRoot, "Installers");
        Directory.CreateDirectory(custom);
        InstallerDownloadLocation.SetCustomDirectory(custom);
        InstallerDownloadLocation.SetCustomDirectory(null);

        Assert.Null(InstallerDownloadLocation.GetCustomDirectory());
        Assert.False(InstallerDownloadLocation.IsCustomDirectorySet);
    }

    [Fact]
    public void ResolveExistingDirectoryCreatesTheCustomDirectory()
    {
        string custom = Path.Combine(_testRoot, "Created");
        InstallerDownloadLocation.SetCustomDirectory(custom);

        Assert.Null(InstallerDownloadLocation.ResolveStartDirectory());
        Assert.Equal(custom, InstallerDownloadLocation.ResolveExistingDirectory());
        Assert.True(Directory.Exists(custom));
        Assert.Equal(custom, InstallerDownloadLocation.ResolveStartDirectory());
    }

    [Fact]
    public void ResolveExistingDirectoryRecreatesAConfiguredDirectoryThatWasDeleted()
    {
        string custom = Path.Combine(_testRoot, "Deleted");
        Directory.CreateDirectory(custom);
        InstallerDownloadLocation.SetCustomDirectory(custom);
        Directory.Delete(custom);

        Assert.Equal(custom, InstallerDownloadLocation.ResolveExistingDirectory());
        Assert.True(Directory.Exists(custom));
    }

    [Fact]
    public void DefaultDirectoryMatchesTheCoreDataDefault()
    {
        Assert.Equal(
            CoreData.UniGetUI_DefaultInstallerDownloadDirectory,
            InstallerDownloadLocation.DefaultDirectory
        );
    }

    [Fact]
    public void TheDefaultDirectoryFollowsTheXdgUserDirectoriesFile()
    {
        string resolved = ResolveWithXdgUserDirs(
            """
            # Generated by xdg-user-dirs-update
            XDG_DESKTOP_DIR="$HOME/Escritorio"
            XDG_DOWNLOAD_DIR="$HOME/Descargas"
            """
        );

        Assert.EndsWith("Descargas", resolved);
        Assert.DoesNotContain("$HOME", resolved);
    }

    [Fact]
    public void TheXdgDownloadDirectoryIsUnescaped()
    {
        string resolved = ResolveWithXdgUserDirs(
            """
            XDG_DOWNLOAD_DIR="$HOME/Des\"car\\gas"
            """
        );

        Assert.EndsWith("""Des"car\gas""", resolved);
        Assert.StartsWith(Environment.GetFolderPath(Environment.SpecialFolder.UserProfile), resolved);
    }

    [Fact]
    public void AnEscapedHomeInTheXdgDownloadDirectoryIsNotExpanded()
    {
        string resolved = ResolveWithXdgUserDirs(
            """
            XDG_DOWNLOAD_DIR="\$HOME/Descargas"
            """
        );

        Assert.Equal("$HOME/Descargas", resolved);
    }

    private string ResolveWithXdgUserDirs(string userDirsContents)
    {
        CoreData.TEST_DownloadsDirectoryOverride = null;
        string configHome = Path.Combine(_testRoot, "config");
        Directory.CreateDirectory(configHome);
        File.WriteAllText(Path.Combine(configHome, "user-dirs.dirs"), userDirsContents);

        string? previousConfigHome = Environment.GetEnvironmentVariable("XDG_CONFIG_HOME");
        string? previousDownloadDir = Environment.GetEnvironmentVariable("XDG_DOWNLOAD_DIR");
        try
        {
            Environment.SetEnvironmentVariable("XDG_CONFIG_HOME", configHome);
            Environment.SetEnvironmentVariable("XDG_DOWNLOAD_DIR", null);
            return InstallerDownloadLocation.DefaultDirectory;
        }
        finally
        {
            Environment.SetEnvironmentVariable("XDG_CONFIG_HOME", previousConfigHome);
            Environment.SetEnvironmentVariable("XDG_DOWNLOAD_DIR", previousDownloadDir);
        }
    }

    [Fact]
    public void TheRealDefaultDirectoryIsAnAbsolutePath()
    {
        CoreData.TEST_DownloadsDirectoryOverride = null;

        string directory = InstallerDownloadLocation.DefaultDirectory;

        Assert.False(string.IsNullOrWhiteSpace(directory));
        Assert.True(Path.IsPathFullyQualified(directory));
    }

    public void Dispose()
    {
        Settings.ResetSettings();
        CoreData.TEST_DataDirectoryOverride = null;
        CoreData.TEST_DownloadsDirectoryOverride = null;
        if (Directory.Exists(_testRoot))
            Directory.Delete(_testRoot, recursive: true);
        GC.SuppressFinalize(this);
    }
}
