namespace UniGetUI.Pages.SettingsPages;

internal static partial class SettingsSearch
{
    private static readonly Entry[] Entries =
    [
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Allow changing the paths for package manager executables", "AllowCustomManagerPaths"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Allow custom command-line arguments", "AllowCLIArguments"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Allow importing custom command-line arguments when importing packages from a bundle", "AllowImportingCLIArguments"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Allow importing custom pre-install and post-install commands when importing packages from a bundle", "AllowImportPrePostOpCommands"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Ask for administrator privileges once for each batch of operations", "DoCacheAdminRightsForBatches"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Ask only once for administrator privileges", "DoCacheAdminRights"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Delegate package operations to the Devolutions Agent broker", "UseAgentBroker"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Ignore custom pre-install and post-install commands when importing packages from a bundle", "AllowPrePostOpCommand"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Administrator), "Prohibit any kind of Elevation via UniGetUI Elevator or GSudo", "ProhibitElevation"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Backup), "Add a timestamp to the backup file names", "EnableBackupTimestamping"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Backup), "Maximum local backups to keep", "MaxLocalBackupCount"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Backup), "Periodically perform a cloud backup of the installed packages", "EnablePackageBackup_CLOUD"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Backup), "Periodically perform a local backup of the installed packages", "EnablePackageBackup_LOCAL"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Backup), "Set a custom backup file name", "ChangeBackupFileName"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Disable the 1-minute timeout for package-related operations", "DisableTimeoutOnPackageListingTasks"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Enable background CPU Usage optimizations (see Pull Request #3278)", "DisableDMWThreadOptimizations"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Enable background api (UniGetUI Widgets and Sharing, port 7058)", "DisableApi"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Perform integrity checks at startup", "DisableIntegrityChecks"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Show UniGetUI's version and build number on the titlebar.", "ShowVersionNumberOnTitlebar"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Use a custom icon and screenshot database URL", "IconDataBaseURL"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Use installed GSudo instead of UniGetUI Elevator", "ForceUserGSudo"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "Wait for the device to be connected to the internet before attempting to do tasks that require internet connectivity.", "DisableWaitForInternetConnection"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Experimental), "When batch installing packages from a bundle, install also packages that are already installed", "InstallInstalledPackagesBundlesPage"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.General), "Hide my username from the logs", "RedactUsernameInLog"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.General), "Install prerelease versions of UniGetUI", "EnableUniGetUIBeta"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.General), "Show the release notes after UniGetUI is updated", "DisableReleaseNotesOnUpdate"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.General), "UniGetUI display language:", "PreferredLanguage"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.General), "Update UniGetUI automatically", "DisableAutoUpdateWingetUI"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Application theme:", "PreferredTheme"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Close UniGetUI to the system tray", "DisableSystemTray"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Navigation menu:", "NavMenuMode"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Select upgradable packages by default", "DisableSelectingUpdatesByDefault"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Show package icons on package lists", "DisableIconsOnPackageLists"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Show the installer download size column", "ShowDownloadSizeColumn"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "Show the installer host column", "ShowInstallerHostColumn"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Interface_P), "UniGetUI startup page:", "StartupPage"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Internet), "Authenticate to the proxy with a user and a password", "EnableProxyAuth"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Internet), "Connect the internet using a custom proxy", "EnableProxy"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Internet), "Proxy URL", "ProxyURL"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Internet), "Wait for the device to be connected to the internet before attempting to do tasks that require internet connectivity.", "DisableWaitForInternetConnection"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Notifications), "Enable UniGetUI notifications", "DisableNotifications"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Notifications), "Show a notification when an operation fails", "DisableUpdatesNotifications"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Notifications), "Show a notification when an operation finishes successfully", "DisableSuccessNotifications"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Notifications), "Show a notification when there are available updates", "DisableUpdatesNotifications"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Notifications), "Show a silent notification when an operation is running", "DisableProgressNotifications"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Ask to delete desktop shortcuts created during an install or upgrade.", "AskToDeleteNewDesktopShortcuts"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Choose how many operations should be performed in parallel", "ParallelOperationCount"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Clear successful operations from the operation list after a 5 second delay", "MaintainSuccessfulInstalls"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Default installer download directory", "DefaultInstallerDownloadDirectory"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Expand environment variables written as %VAR% (instead of <VAR>)", "ExpandEnvVarsWithPercentSyntax"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Installer filenames", "InstallerFileNameScheme"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Manage Start Menu shortcuts", "AskAboutNewStartMenuShortcuts"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Operations), "Try to kill the processes that refuse to close when requested to", "KillProcessesThatRefuseToDie"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Scheduler), "Manage automatic updates", "AutoUpdates"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Scheduler), "Scheduled maintenance", "MaintenanceSchedules"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Check for package updates periodically", "DisableAutoCheckforUpdates"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Check for updates every:", "UpdatesCheckInterval"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Do not automatically install updates when the battery saver is on", "DisableAUPOnBatterySaver"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Do not automatically install updates when the device runs on battery", "DisableAUPOnBattery"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Do not automatically install updates when the network connection is metered", "DisableAUPOnMeteredConnections"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Install available updates automatically", "AutomaticallyUpdatePackages"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Minimum age for updates", "MinimumUpdateAge"),
        new(typeof(UniGetUI.Pages.SettingsPages.GeneralPages.Updates), "Warn me when the installer URL host changes between the installed version and the new version (WinGet only)", "DisableInstallerHostChangeWarning"),
    ];
}
